Capstone.Web/Models/Survey.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Capstone.Web.Models
{
    public class Survey
    {
        public Park park { get; set; }
        /// <summary>
        /// the ID assigned to a survey
        /// </summary>
        public int SurveyId { get; set; }


        /// <summary>
        /// the code assigned to the park that the user decided to vote on
        /// </summary>

        [Required]
        public string ParkCode { get; set; }

        public string ParkName { get; set; }

        /// <summary>
        /// the email address of the user taking the survey
        /// </summary>
        [EmailAddress]
        [Required]
        public string Email { get; set; }

        /// <summary>
        /// the physical activity level of the user taking the survey.
        ///  (inactive, sedentary, active, extremely active)
        /// </summary>
        public string ActivityLevel { get; set; }

        //public int SurveyCount

        //public SelectList Parks { get; set; }

        public IList<SelectListItem> Parks = new List<SelectListItem>
        {
                new SelectListItem() {Text="Glacier National Park", Value="GNP"},
                new SelectListItem() { Text="Grand Canyon National Park", Value="GCNP"},
                new SelectListItem() { Text="Grand Teton National Park", Value="GTNP"},
                new SelectListItem() { Text="Mount Ranier National Park", Value="MRNP"},
                new SelectListItem() { Text="Great Smoky Mountain National Park", Value="GSMNP"},
                new SelectListItem() { Text="Everglades National Park", Value="ENP"},
                new SelectListItem() { Text="Yelllowstone National Park", Value="YNP"},
                new SelectListItem() { Text="Yosemite National Park", Value="YNP2"},
                new SelectListItem() { Text="Cuyahoga Valley National Park", Value="CVNP"},
                  new SelectListItem() { Text="Rocky Mountain National Park", Value="RMNP"}
        };

        /// <summary>
        /// the state of residence of the user taking the survey
        /// </summary>
        /// 
   
        public string State { get; set; }

        [Required]
        public IList<SelectListItem> States = new List<SelectListItem>
        {
                new SelectListItem() {Text="Alabama", Value="AL"},
                new SelectListItem() { Text="Alaska", Value="AK"},
                new SelectListItem() { Text="Arizona", Value="AZ"},
                new SelectListItem() { Text="Arkansas", Value="AR"},
                new SelectListItem() { Text="California", Value="CA"},
                new SelectListItem() { Text="Colorado", Value="CO"},
                new SelectListItem() { Text="Connecticut", Value="CT"},
                new SelectListItem() { Text="District of Columbia", Value="DC"},
                new SelectListItem() { Text="Delaware", Value="DE"},
                new SelectListItem() { Text="Florida", Value="FL"},
                new SelectListItem() { Text="Georgia", Value="GA"},
                new SelectListItem() { Text="Hawaii", Value="HI"},
                new SelectListItem() { Text="Idaho", Value="ID"},
                new SelectListItem() { Text="Illinois", Value="IL"},
                new SelectListItem() { Text="Indiana", Value="IN"},
                new SelectListItem() { Text="Iowa", Value="IA"},
                new SelectListItem() { Text="Kansas", Value="KS"},
                new SelectListItem() { Text="Kentucky", Value="KY"},
                new SelectListItem() { Text="Louisiana", Value="LA"},
                new SelectListItem() { Text="Maine", Value="ME"},
                new SelectListItem() { Text="Maryland", Value="MD"},
                new SelectListItem() { Text="Massachusetts", Value="MA"},
                new SelectListItem() { Text="Michigan", Value="MI"},
                new SelectListItem() { Text="Minnesota", Value="MN"},
                new SelectListItem() { Text="Mississippi", Value="MS"},
                new SelectListItem() { Text="Missouri", Value="MO"},
                new SelectListItem() { Text="Montana", Value="MT"},
                new SelectListItem() { Text="Nebraska", Value="NE"},
                new SelectListItem() { Text="Nevada", Value="NV"},
                new SelectListItem() { Text="New Hampshire", Value="NH"},
                new SelectListItem() { Text="New Jersey", Value="NJ"},
                new SelectListItem() { Text="New Mexico", Value="NM"},
                new SelectListItem() { Text="New York", Value="NY"},
                new SelectListItem() { Text="North Carolina", Value="NC"},
                new SelectListItem() { Text="North Dakota", Value="ND"},
                new SelectListItem() { Text="Ohio", Value="OH"},
                new SelectListItem() { Text="Oklahoma", Value="OK"},
                new SelectListItem() { Text="Oregon", Value="OR"},
                new SelectListItem() { Text="Pennsylvania", Value="PA"},
                new SelectListItem() { Text="Rhode Island", Value="RI"},
                new SelectListItem() { Text="South Carolina", Value="SC"},
                new SelectListItem() { Text="South Dakota", Value="SD"},
                new SelectListItem() { Text="Tennessee", Value="TN"},
                new SelectListItem() { Text="Texas", Value="TX"},
                new SelectListItem() { Text="Utah", Value="UT"},
                new SelectListItem() { Text="Vermont", Value="VT"},
                new SelectListItem() { Text="Virginia", Value="VA"},
                new SelectListItem() { Text="Washington", Value="WA"},
                new SelectListItem() { Text="West Virginia", Value="WV"},
                new SelectListItem() { Text="Wisconsin", Value="WI"},
                new SelectListItem() { Text="Wyoming", Value="WY"}

        };
    }

}





Capstone.Web/Models/SurveyResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Capstone.Web.Models
{
    public class SurveyResponse
    {
        public Survey survey { get; set; }
        /// <summary>
        /// the code assigned to the park that the user decided to vote on
        /// </summary>
        public string ParkCode { get; set; }


        /// <summary>
        /// the name of the park
        /// </summary>
        public string ParkName { get; set; }

        /// <summary>
        /// the count of votes for a particular park
        /// </summary>
        public int VotesForPark { get; set; }
      
    }
}

Capstone.Web/Controllers/SurveyController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Capstone.Web.DAL;
using Capstone.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Capstone.Web.Controllers
{
    public class SurveyController : Controller
    {
        private IParkDAO parkDAO;
        private IWeatherDAO weatherDAO;
        private ISurveyDAO surveyDAO;

        public SurveyController(IParkDAO parkDAO, IWeatherDAO weatherDAO, ISurveyDAO surveyDAO)
        {
            this.parkDAO = parkDAO;
            this.weatherDAO = weatherDAO;
            this.surveyDAO = surveyDAO;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult NewSurvey()
        {
            //IList<Park> parks = parkDAO.GetAllParks();
            Survey survey = new Survey();

            // vm.Parks 
            //survey.Parks = new SelectList(parks, "ParkCode", "ParkName");
            return View(survey);
        }

        [HttpPost]
        public ActionResult NewSurvey(Survey newSurvey)
        {
            surveyDAO.SaveSurvey(newSurvey);

            return RedirectToAction("SurveyResponse");
        }

        public ActionResult SurveyResponse()
        {
            List<SurveyResponse> surveys = surveyDAO.GetTopParks();


            return View(surveys);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Capstone.Web/Views/Survey/NewSurvey.cshtml
@model Survey
@{
    ViewData["Title"] = "NewSurvey";
    
}
<div class="feedback">
<h4>Please vote for your favorite park in the survey below.</h4>
    </div>

<div class="row">
    <div class="col-md-4">
        <form asp-controller="Survey" asp-action="NewSurvey" method="post">

            <p>
                <label asp-for="park.ParkName">Favorite Park</label>
                <select asp-for="ParkCode" asp-items="Model.Parks">
                <option value="">*** Please select a park ***</option>
                </select>
                <span asp-validation-for="ParkCode"></span>
            </p>
            <p>
                <label asp-for="Email">Enter your email address</label>
                <input type="text" id="Email" asp-for="Email" />
                <span asp-validation-for="Email"></span>
            </p>
            <p>
                <label asp-for="State">Which state do you live in?</label> 
                <select asp-for="State" asp-items="Model.States">
                        <option value="">*** Please select a state ***</option>
                    </select>
                <span asp-validation-for="State"></span>

            </p>
            
            <div class="activityLevel">
                    <label asp-for="@Model.ActivityLevel">Which of the following best describes your activity level?</label>
                    <div class="radio-button">
                        <input asp-for="ActivityLevel" type="radio" value="inactive" /> inactive
                    </div>
                    <div class="radio-button">
                        <input asp-for="ActivityLevel" type="radio" value="sedentary" /> sedentary
                    </div>
                    <div class="radio-button">
                        <input asp-for="ActivityLevel" type="radio" value="active" /> active
                    </div>
                    <div class="radio-button">
                        <input asp-for="ActivityLevel" type="radio" value="extremely active" /> extremely active
                    </div>
                    <span asp-validation-for="ActivityLevel"></span>
         </div>

            <div>
                <input type="submit" value="Submit Survey!" class="btn btn-default" />
            </div>
        </form>

    </div>
</div>


Capstone.Web/Views/Survey/SurveyResponse.cshtml
@model IList<SurveyResponse>
@{
    ViewData["Title"] = "SurveyResponse";
}

<div class="surveyResponse"
<h4>Thanks for completing our survey!</h4>

<h2>Park Ranking</h2>

<p>Check out our top-ranked national parks! To find out more about a park, click on its name or picture. </p>
    </div>

<div class="top-ranked-parks">
    @{

        foreach (SurveyResponse sr in Model)
        {
        <div class="parksSurvey">
            <div class="park-info">
                <div class="park-name">
                    <p>
                        @sr.ParkName -

                        <strong>Number of Votes: @sr.VotesForPark</strong>
                    </p>
                </div>

            </div>
            <div class="park-pic">
                <a asp-controller="Home" asp-action="Detail" asp-route-parkCode="@sr.ParkCode"><img src="~/images/parks/@(sr.ParkCode).jpg" class="park-image" /></a>
            </div>
    
            
        </div>
        }
    }
</div>
